language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip3 install -r requirements.txt

# command to run tests
script:
<<<<<<< HEAD
  - pytest --cov=program 
=======
  - pytest --cov=test_main
>>>>>>> 3d17609a4aba602d69c308ce5391762246b86e9c
#Command to use coverage 
after_success:
  - coveralls
