language: python
python:
<<<<<<< HEAD
  - '3.6'
  - '3.7'
  - '3.8'
jobs:
  include:
  - python: "3.7"
    env: TEST_SUITE=suite_3_7
  - python: "3.6"
    env: TEST_SUITE=suite_3_6
  - python: "3.8"
    env: TEST_SUITE=suite_3_8
script: ./test.py $TEST_SUITE
=======
  - "3.8"
# command to install dependencies
install:
  - pip3 install -r requirements.txt

# command to run tests
script:
  - pytest --cov=program 
#Command to use coverage 
after_success:
  - coveralls
>>>>>>> master
